import sizes from "./sizeHelpers";

const styles = {
  Color: {
    width: "20%",
    display: "inline-block",
    height: (props) => (props.showMore ? "25%" : "50%"),
    margin: "0 auto",
    position: "relative",
    cursor: "pointer",
    fontFamily: "Roboto, sans-serif",
    fontWeight: "100",
    letterSpacing: "2px",
    "&:hover button": {
      opacity: "1",
    },
    [sizes.down("md")]: {
      width: "50%",
      height: (props) => (props.showMore ? "20%" : "30%"),
    },
    [sizes.down("xs")]: {
      width: "100%",
      height: (props) => (props.showMore ? "15%" : "20%"),
    },
  },

  ColorCopy: {
    position: "absolute",
    width: "40%",
    height: (props) => (props.showMore ? "20%" : "10%"),
    display: "inline block",
    top: "50%",
    left: "50%",
    marginLeft: "-20%",
    marginTop: "-5%",
    backgroundColor: "rgba(255, 255, 255, 0.45)",
    border: "none",
    letterSpacing: "1px",
    textTransform: "uppercase",
    transition: "0.4s",
    color: "white",
    cursor: "pointer",
    opacity: "0",
  },
  backBtn: {
    opacity: "1",
    height: "10%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    textDecoration: "none",
  },
  ColorName: {
    position: "absolute",
    left: "0",
    bottom: "0px",
    margin: "5px",
    textTransform: "uppercase",
    fontSize: "12px",
    fontWeight: "600",
  },
  ColorMore: {
    right: "0",
    bottom: "0",
    position: "absolute",
    backgroundColor: "rgba(255, 255, 255, 0.3)",
    padding: "1% 7%",
    color: "black",
  },
  grow: {
    zIndex: "0",
    height: "100%",
    width: "100%",
    transition: "transform 0.6s ease-in-out",
    opacity: " 0",
    transform: "scale(0.1)",
  },
  growActive: {
    zIndex: "10",
    transform: "scale(10)",
    opacity: "1",
    position: "absolute",
  },
  CopyMsg: {
    flexDirection: "column",
    position: "fixed",
    right: "0",
    left: "0",
    bottom: "0",
    top: "0",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: "0",
    opacity: "0",
    transform: "scale(0.1)",
  },
  CopyMsgH1: {
    color: "white",
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    width: "100%",
    textAlign: "center",
    padding: "10px",
    textShadow: "2px 4px black",
    fontSize: "4em",
    zIndex: "25",
  },
  CopyMsgP: {
    fontSize: "2em",
  },
  CopyMsgShow: {
    opacity: "1",
    transform: "scale(1)",
    transition: "all 0.4s ease-in-out",
    transitionDelay: "0.3s",
    zIndex: "25",
  },
};

export default styles;
